version: '3'
services:
  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    image: front-end-image
    expose:
      - "9000"

  back-end:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    image: back-end-image
    expose:
      - "5252"

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    image: proxy-image
    ports:
      - "80:80"
    depends_on:
      - front-end
      - back-end